# Node.js React Web App to Linux on Azure
# Build a Node.js React app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pool:
  name: Local-Joakim

variables:
  # Make storybook group available.
  - group: 'Storyblok'

  # Azure Resource Manager connection created during pipeline creation
  - name: azureSubscription
    value: 'bb781f30-4924-43cf-bd9a-5d52e8991ea0'

  # Web app name on Azure
  - name: webAppName
    value: 'amaceitwebstage01'

  # Environment name
  # environmentName: 'stage'

  # Agent VM image name
  - name: image
    value: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build stage
    # TODO: Remove job wrapper later.... :)
    jobs:
      - job: Build
        displayName: Build
        steps:
          # Install Node.js and build
          - task: NodeTool@0
            displayName: 'Install Node.js from nvmrc file'
            inputs:
              versionSource: "fromFile"
              versionFilePath: ".nvmrc"

          - task: Npm@1
            inputs:
              command: 'ci'
              workingDir: '.'
              verbose: true

          - bash: |
              # Use the API and agent variables from the Storyblok group
              apiValue=$(STORYBLOK_API_TOKEN)
              imageValue=$(image)
              echo "API Value: $apiValue"
              echo "Image Value: $imageValue"

              # Set environment variable for npm script
              echo "STORYBLOK_API=$apiValue" >> $(Agent.BuildDirectory)/.env
            displayName: 'Set API variable for npm'

          - script: | # Replace with build-ci for consistent build
              npm ci
            displayName: 'npm install dependencies for production'
            enabled: false
          
          - task: Cache@2
            displayName: 'Caching dependencies for future builds'
            inputs:
              key: next | $(Agent.OS) | package-lock.json
              path: '$(System.DefaultWorkingDirectory)/.next/cache'
          
          # Just for som debugging
          - task: Bash@3
            displayName: Display files in Build directory
            inputs:
              targetType: 'inline'
              script: |
                echo "Showing AFTER copying"
                echo $(Agent.BuildDirectory)
                ls -la $(Agent.BuildDirectory)
          
          - script: | # Replace with build-ci for consistent build
              STORYBLOK_API_TOKEN=$(STORYBLOK_API_TOKEN) 
              npm run build
            displayName: 'build the application and pre-render pages'

          # Copy files to: $(Build.ArtifactStagingDirectory)
          - task: CopyFiles@2
            displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
            inputs:
              SourceFolder: '.'
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'

          # Just for som debugging
          - task: Bash@3
            displayName: Showing BEFORE compressing
            inputs:
              targetType: 'inline'
              script: |
                echo $(Build.ArtifactStagingDirectory)
                ls -la $(Build.ArtifactStagingDirectory)

          # ZIP files
          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              replaceExistingArchive: true

          # Make the files available for the next job # TODO: Remove!
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: drop'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              ArtifactName: 'drop'
              publishLocation: 'Container'

          - task: AzureWebApp@1
            displayName: Deploy it!
            inputs:
              azureSubscription: 'amaceit web (bb781f30-4924-43cf-bd9a-5d52e8991ea0)'
              appType: 'webAppLinux'
              appName: 'amaceitwebstage01'
              package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              runtimeStack: 'NODE|18-lts'
              startUpCommand: "pm2 start /home/site/wwwroot/ecosystem.config.js --no-daemon --env DEBUG='*'"
