trigger: none

pool:
  name: Azure Pipelines
steps:
  - task: NodeTool@0
    displayName: 'Use Node 18.x'
    inputs:
      versionSpec: 18.x

  - task: Npm@1
    displayName: 'npm custom'
    inputs:
      command: custom
      workingDir: '$(Build.SourcesDirectory)'
      verbose: false
      customCommand: 'install --global gatsby-cli'
    enabled: false

  - task: Npm@1
    displayName: 'npm install'
    inputs:
      workingDir: '$(Build.SourcesDirectory)'
      verbose: false

  - task: Npm@1
    displayName: 'npm build'
    inputs:
      command: custom
      workingDir: '$(Build.SourcesDirectory)'
      verbose: false
      customCommand: 'run build'
