# Node.js React Web App to Linux on Azure
# Build a Node.js React app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none

pr:
  - main

pool:
  name: Local-Joakim

variables:
  # Make storybook group available.
  - group: 'Storyblok'

  # Agent VM image name
  - name: image
    value: 'ubuntu-latest'

  # Agent VM image name
  - name: artifactName
    value: 'drop'

jobs:
  - job: install
    displayName: Install node and lint repo
    steps:
      - task: NodeTool@0
        displayName: 'Install Node.js from nvmrc file'
        inputs:
          versionSource: 'fromFile'
          versionFilePath: '.nvmrc'

      - task: Cache@2
        displayName: 'Retrieving cache for package-lock.json'
        inputs:
          key: 'package-lock.json'
          path: '$(System.DefaultWorkingDirectory)/.next/cache'

      - task: Npm@1
        displayName: 'Install dependencies for production'
        inputs:
          command: 'ci'

      - bash: |
          # Use the API and agent variables from the Storyblok group
          apiValue=$(STORYBLOK_API_TOKEN)
          # Set environment variable for npm script
          echo "STORYBLOK_API_TOKEN=$apiValue" >> $(System.DefaultWorkingDirectory)/.env
        displayName: 'Set API variable for npm'

      - task: Npm@1
        displayName: Lint application
        inputs:
          command: 'custom'
          workingDir: '.'
          customCommand: 'run lint'

      - task: Npm@1
        displayName: 'Run unit tests'
        inputs:
          command: 'custom'
          customCommand: 'run test:ci'

      - script: |
          npx playwright install --with-deps
        displayName: 'Prepare E2E tests'

      - task: Npm@1
        displayName: 'Run E2E tests'
        inputs:
          command: 'custom'
          customCommand: 'CI=true && npx playwright test'
