parameters:
  - name: environment
    type: string
    default: 'development'
    values:
      - development
      - stage
      - prod 
      
trigger: none # We don't want this to run on pushes

pr:
  - main
  - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: 'Storyblok'
  - group: 'AzureEmail'
  - group: 'Mailtrap'
  - group: 'App'
  - name: NPM_CACHE_FOLDER
    value: $(Pipeline.Workspace)/.npm
  - name: NEXT_CACHE_FOLDER
    value: $(System.DefaultWorkingDirectory)/.next/cache
  - name: PLAYWRIGHT_BROWSERS_PATH
    value: $(Pipeline.Workspace)/playwright-browsers

stages:
  - stage: Verify
    jobs:
      - job: TestAndLint
        steps:
          - task: NodeTool@0
            displayName: 'Install Node.js from .nvmrc'
            inputs:
              versionSource: 'fromFile'
              versionFilePath: '.nvmrc'

          - task: Bash@3
            displayName: 'Create .env file'
            inputs:
              targetType: 'inline'
              script: |
                cat << EOF > .env
                STORYBLOK_API_ENVIRONMENT=$(STORYBLOK_API_ENVIRONMENT)
                STORYBLOK_API_TOKEN=$(STORYBLOK_API_TOKEN)
                MAILTRAP_API_USER=$(MAILTRAP_API_USER)
                MAILTRAP_API_PASSWORD=$(MAILTRAP_API_PASSWORD)
                MAILTRAP_API_TOKEN=$(MAILTRAP_API_TOKEN)
                MAILTRAP_INBOX_ID=$(MAILTRAP_INBOX_ID)
                MAILTRAP_ACCOUNT_ID=$(MAILTRAP_ACCOUNT_ID)
                AZURE_EMAIL_CONNECTION_STRING=$(AZURE_EMAIL_CONNECTION_STRING)
                AZURE_EMAIL_SENDER_ADDRESS=$(AZURE_EMAIL_SENDER_ADDRESS)
                AZURE_EMAIL_FORM_RECIEVER_ADDRESS=$(AZURE_EMAIL_FORM_RECIEVER_ADDRESS)
                APP_URL=$(APP_URL_DEV)
                EOF

          - task: Cache@2
            displayName: 'Cache npm packages'
            inputs:
              key: 'npm | "$(Agent.OS)" | package-lock.json'
              restoreKeys: |
                npm | "$(Agent.OS)"
              path: $(NPM_CACHE_FOLDER)
            condition: always()

          - task: Cache@2
            displayName: 'Cache Playwright browsers'
            inputs:
              key: 'playwright-browsers | "$(Agent.OS)" | package-lock.json'
              restoreKeys: |
                playwright-browsers | "$(Agent.OS)"
              path: $(PLAYWRIGHT_BROWSERS_PATH)

          - task: Npm@1
            displayName: 'npm ci'
            inputs:
              command: 'ci'

          - task: Cache@2
            displayName: 'Cache next build'
            inputs:
              key: 'nextjs | "$(Agent.OS)" | package-lock.json'
              restoreKeys: |
                npm | "$(Agent.OS)"
              path: $(NEXT_CACHE_FOLDER)
            condition: always()

          - task: Npm@1
            displayName: 'Lint'
            inputs:
              command: 'custom'
              customCommand: 'run lint'

          - task: Npm@1
            displayName: 'Unit Tests'
            inputs:
              command: 'custom'
              customCommand: 'run test:ci'

          - script: |
              npx playwright install --with-deps
            displayName: 'Install Playwright'

          - task: Npm@1
            displayName: 'E2E Tests'
            inputs:
              command: 'custom'
              customCommand: 'run test:e2e'
            env:
              CI: 'true'
              PLAYWRIGHT_BROWSERS_PATH: $(PLAYWRIGHT_BROWSERS_PATH)
