#
# A standalone build which  includes
# all the static files and assets
# needed to run the application.
#

trigger:
  - 'main'

pool:
  name: Azure Pipelines

variables:
  # Make storybook group available.
  - group: 'Storyblok'
  - group: 'AzureEmail'
  - group: 'Mailtrap'
  - group: 'App'

  # Azure Resource Manager connection created during pipeline creation
  - name: azureSubscription
    value: 'amaceit web (bb781f30-4924-43cf-bd9a-5d52e8991ea0)'

  # Web app name on Azure
  - name: webAppName
    value: 'amaceitwebprod01'

  # Agent VM image name
  - name: image
    value: 'ubuntu-latest'

  # Agent VM image name
  - name: artifactName
    value: 'drop'

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        steps:
          - bash: |
              echo "STORYBLOK_API_TOKEN=$(STORYBLOK_API_TOKEN)" >> $(envfile)

              echo "MAILTRAP_API_USER=$(MAILTRAP_API_USER)" >> $(envfile)
              echo "MAILTRAP_API_PASSWORD=$(MAILTRAP_API_PASSWORD)" >> $(envfile)
              echo "MAILTRAP_API_TOKEN=$(MAILTRAP_API_TOKEN)" >> $(envfile)
              echo "MAILTRAP_INBOX_ID=$(MAILTRAP_INBOX_ID)" >> $(envfile)
              echo "MAILTRAP_ACCOUNT_ID=$(MAILTRAP_ACCOUNT_ID)" >> $(envfile)

              echo "AZURE_EMAIL_CONNECTION_STRING=$(AZURE_EMAIL_CONNECTION_STRING)" >> $(envfile)
              echo "AZURE_EMAIL_SENDER_ADDRESS=$(AZURE_EMAIL_SENDER_ADDRESS)" >> $(envfile)
              echo "AZURE_EMAIL_FORM_RECIEVER_ADDRESS=$(AZURE_EMAIL_FORM_RECIEVER_ADDRESS)" >> $(envfile)

              echo "APP_DOMAIN=$(APP_DOMAIN)" >> $(envfile)
              echo "APP_URL=$(APP_URL)" >> $(envfile)

            displayName: 'Set API variable for npm'

          # Install Node.js and build
          - task: NodeTool@0
            displayName: 'Install Node.js from nvmrc file'
            inputs:
              versionSource: 'fromFile'
              versionFilePath: '.nvmrc'

          - task: Cache@2
            displayName: 'Retrieving cache for package-lock.json'
            inputs:
              key: 'package-lock.json'
              path: '$(System.DefaultWorkingDirectory)/.next/cache'

          - task: Npm@1
            displayName: 'Install dependencies for production'
            inputs:
              command: 'ci'

          - task: Npm@1
            displayName: Build application
            inputs:
              command: 'custom'
              workingDir: '.'
              customCommand: 'run build'

          - task: CopyFiles@2
            displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
            inputs:
              SourceFolder: '.next/standalone'
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'

          - task: CopyFiles@2
            displayName: 'Copy .env and ecoystem to: $(Build.ArtifactStagingDirectory)'
            inputs:
              Contents: |
                ecosystem.config.js
                .env
              TargetFolder: '$(Build.ArtifactStagingDirectory)'

          # Needed for standalone build if not using CDN
          - task: CopyFiles@2
            displayName: 'Copy .next/static to: $(Build.ArtifactStagingDirectory).next/static'
            inputs:
              SourceFolder: '.next/static'
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)/.next/static'

          # Needed for standalone build if not using CDN
          - task: CopyFiles@2
            displayName: 'Copy /public to: $(Build.ArtifactStagingDirectory)/public'
            inputs:
              SourceFolder: 'public'
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)/public'

          - task: ArchiveFiles@2
            displayName: 'Zip files'
            inputs:
              rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              replaceExistingArchive: true

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: drop'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              ArtifactName: $(artifactName)
              publishLocation: 'Container'

  - stage: Validation
    displayName: Validate deploy
    dependsOn: Build
    jobs:
      - job: waitForValidation
        displayName: Wait for Manual approval
        pool: server
        timeoutInMinutes: 60 # job times out in 1 hour
        steps:
          - task: ManualValidation@0
            timeoutInMinutes: 30
            inputs:
              notifyUsers: 'joakim.nystrom@amaceit.com'
              instructions: 'Approve deploy to PRODUCTION ✅'
              onTimeout: 'reject'

  - stage: Deploy
    displayName: Deploy to stage
    dependsOn: Validation
    jobs:
      - job: deploy
        displayName: Deploy to server
        pool: Azure Pipelines
        steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download Build Artifacts'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: $(artifactName)
              downloadPath: '$(System.ArtifactsDirectory)'

          - task: AzureWebApp@1
            displayName: Upload zip to server
            inputs:
              azureSubscription: $(azureSubscription)
              appType: 'webAppLinux'
              appName: $(webAppName)
              package: '$(System.ArtifactsDirectory)/$(artifactName)/**/*.zip'
              runtimeStack: 'NODE|18-lts'
              startUpCommand: "pm2 start /home/site/wwwroot/ecosystem.config.js --no-daemon --env DEBUG='*'"
              appSettings: '-STORYBLOK_API_TOKEN $(STORYBLOK_API_TOKEN)' #Assigning environment variable
