# Node.js React Web App to Linux on Azure
# Build a Node.js React app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none

pr:
  - develop
  - main

pool:
  name: Azure Pipelines
  # name: Local-Joakim

variables:
  # Make storybook group available.
  - group: 'Storyblok'
  - group: 'AzureEmail'
  - group: 'Mailtrap'
  - group: 'App'

  # Agent VM image name
  - name: image
    value: 'ubuntu-latest'

  - name: envfile
    value: $(System.DefaultWorkingDirectory)/.env

jobs:
  - job: install
    displayName: Install node and lint repo
    steps:
      - bash: |
          echo "STORYBLOK_API_TOKEN=$(STORYBLOK_API_TOKEN)" >> $(envfile)

          echo "MAILTRAP_API_USER=$(MAILTRAP_API_USER)" >> $(envfile)
          echo "MAILTRAP_API_PASSWORD=$(MAILTRAP_API_PASSWORD)" >> $(envfile)
          echo "MAILTRAP_API_TOKEN=$(MAILTRAP_API_TOKEN)" >> $(envfile)
          echo "MAILTRAP_INBOX_ID=$(MAILTRAP_INBOX_ID)" >> $(envfile)
          echo "MAILTRAP_ACCOUNT_ID=$(MAILTRAP_ACCOUNT_ID)" >> $(envfile)

          echo "AZURE_EMAIL_CONNECTION_STRING=$(AZURE_EMAIL_CONNECTION_STRING)" >> $(envfile)
          echo "AZURE_EMAIL_SENDER_ADDRESS=$(AZURE_EMAIL_SENDER_ADDRESS)" >> $(envfile)
          echo "AZURE_EMAIL_FORM_RECIEVER_ADDRESS=$(AZURE_EMAIL_FORM_RECIEVER_ADDRESS)" >> $(envfile)

          echo "APP_DOMAIN=$(APP_DOMAIN)" >> $(envfile)
          echo "APP_URL=$(APP_URL)" >> $(envfile)

        displayName: 'Set API variable for npm'

      - task: NodeTool@0
        displayName: 'Install Node.js from nvmrc file'
        inputs:
          versionSource: 'fromFile'
          versionFilePath: '.nvmrc'

      - task: Cache@2
        displayName: 'Retrieving cache for package-lock.json'
        inputs:
          key: 'package-lock.json'
          path: '$(System.DefaultWorkingDirectory)/.next/cache'

      - task: Npm@1
        displayName: 'Install dependencies for production'
        inputs:
          command: 'ci'

      - bash: |
          # Use the API and agent variables from the Storyblok group
          apiValue=$(STORYBLOK_API_TOKEN)
          # Set environment variable for npm script
          echo "STORYBLOK_API_TOKEN=$apiValue" >> $(System.DefaultWorkingDirectory)/.env
        displayName: 'Set API variable for npm'

      - task: Npm@1
        displayName: Lint application
        inputs:
          command: 'custom'
          workingDir: '.'
          customCommand: 'run lint'

      - task: Npm@1
        displayName: 'Run unit tests'
        inputs:
          command: 'custom'
          customCommand: 'run test:ci'

      - script: |
          npx playwright install --with-deps
        displayName: 'Prepare E2E tests'

      - script: npx playwright test
        displayName: 'Run E2E tests'
        env:
          CI: true
