sonar.projectKey=RamjanthaP_MediumContext
sonar.organization=ramjanthap-1

sonar.sources=src/pages/services
sonar.inclusions=src/pages/services/index.tsx

sonar.sourceEncoding=UTF-8

sonar.token=a885fc4d0f79d6a981724b4d32a886f444e5f015