import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
import { storyblokInit, apiPlugin } from "@storyblok/react/rsc";
import StoryblokProvider from "./components/StoryblokProvider";
import Config from "./components/Menu/Config";
import Footer from "./components/Footer";
import { getStoryblokConfig } from "@/services/getStoryBlokPage";

storyblokInit({
  accessToken: "isvrOVvrEDwbKVLqsr0E7wtt",
  use: [apiPlugin],
  apiOptions: {
    region: "eu",
  },
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const props = await getStoryblokConfig();
  return (
    <html lang="en">
      <StoryblokProvider>
        <body className={inter.className}>
          <Config blok={props.props.config} />
          {children}
          <Footer />
        </body>
      </StoryblokProvider>
    </html>
  );
}
