import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
import { storyblokInit, apiPlugin } from "@storyblok/react/rsc";
import StoryblokProvider from "@/components/StoryblokProvider";
import Config from "@/components/Menu/Config";
import { getStoryblokConfig } from "@/services/getStoryBlokPage";
import { ThemeSwitcher } from "@/components/DevUtils/ThemeSwitcher";
import Footer from "@/components/Footer/Footer";

storyblokInit({
  accessToken: process.env.STORYBLOK_API_TOKEN,
  use: [apiPlugin],
  apiOptions: {
    region: "eu",
  },
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const config = await getStoryblokConfig();
  return (
    <html lang="en">
      <StoryblokProvider>
        <body className={inter.className}>
          <Config blok={config} />
          {children}
          {process.env.NODE_ENV === "development" && <ThemeSwitcher />}
          <Footer />
        </body>
      </StoryblokProvider>
    </html>
  );
}
