#
# A standalone build which  includes
# all the static files and assets
# needed to run the application.
#

trigger:
  - 'develop'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: parts/variables.yml
  - template: parts/variables-env--stage.yml
  - template: parts/variables-path.yml

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        steps:
          - template: parts/setup-environment.yml
          - template: parts/cache.yml

          - task: Npm@1
            displayName: 'Install dependencies for production'
            inputs:
              command: 'ci'

          - task: Npm@1
            displayName: Build application
            inputs:
              command: 'custom'
              workingDir: '.'
              customCommand: 'run build'

          - template: parts/create-artifact.yml

  - stage: Approval
    displayName: Approve deploy
    dependsOn: Build
    jobs:
      - job: waitForValidation
        displayName: Wait for Manual approval
        pool: server
        timeoutInMinutes: 60 # job times out in 1 hour
        steps:
          - task: ManualValidation@0
            timeoutInMinutes: 30
            inputs:
              notifyUsers: 'joakim.nystrom@amaceit.com' ## TODO make this a variable
              instructions: 'Approve deploy to STAGE' ## TODO make this dynamic
              onTimeout: 'reject'

  - stage: Deploy
    displayName: Deploy to Stage
    dependsOn: Approval
    jobs:
      - deployment: DeployWebApp
        displayName: Deploy Web App
        environment: 'staging'
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: $(ARTIFACT_NAME)

                - task: AzureWebApp@1
                  displayName: 'Deploy to Azure Web App'
                  inputs:
                    azureSubscription: $(AZURE_SUBSCRIPTION)
                    appName: $(AZURE_WEB_APP_NAME)
                    appType: 'webAppLinux'
                    package: '$(Pipeline.Workspace)/$(ARTIFACT_NAME)/$(Build.BuildId).zip'
                    runtimeStack: 'NODE|20-lts'
                    startUpCommand: "pm2 start /home/site/wwwroot/ecosystem.config.js --no-daemon --env DEBUG='*'"
                    appSettings: '-STORYBLOK_API_TOKEN $(STORYBLOK_API_TOKEN)'
# Disabled due to IAM access restrictions

# - stage: Validation
#   displayName: Validation of deploy
#   dependsOn: Deploy
#   jobs:
#     - job:
#       displayName: 'Smoke test'
#       steps:
#       - task: NodeTool@0
#         inputs:
#           versionSpec: '20.x'
#         displayName: 'Install Node.js 20.x'

#       - task: Npm@1
#         displayName: 'Install dependencies for smoke test'
#         inputs:
#           command: 'install'
#           workingDir: '$(System.DefaultWorkingDirectory)/ci/tests'

#       - script: |
#           echo "Running smoke test..."
#           APP_HOSTNAME=$(AZURE_WEB_APP_NAME).azurewebsites.net node smoke-test.js
#         workingDirectory: '$(System.DefaultWorkingDirectory)/ci/tests'
#         displayName: 'Run smoke test'
#         env:
#           APP_HOSTNAME: $(AZURE_WEB_APP_NAME).azurewebsites.net
