trigger: none # We don't want this to run on pushes

pr:
  - main
  - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: ci/parts/variables.yml
  - template: ci/parts/variables-condition.yml
  - template: ci/parts/variables-path.yml

stages:
  - stage: Verify
    jobs:
      - job: TestAndLint
        steps:
          - template: ci/parts/setup-environment.yml
          - template: ci/parts/cache.yml

          - task: Npm@1
            displayName: 'npm ci'
            inputs:
              command: 'ci'

          - template: ci/parts/tests-lint-unit.yml

          - template: ci/parts/tests-e2e.yml
