steps:
  - task: NodeTool@0
    displayName: 'Install Node.js from .nvmrc'
    inputs:
      versionSource: 'fromFile'
      versionFilePath: '.nvmrc'

  - task: Bash@3
    displayName: 'Create .env file'
    inputs:
      targetType: 'inline'
      script: |
        cat << EOF > .env
        STORYBLOK_API_ENVIRONMENT=$(STORYBLOK_API_ENVIRONMENT)
        NEXT_PUBLIC_STORYBLOK_API_TOKEN=$(STORYBLOK_API_TOKEN)
        MAILTRAP_API_TOKEN=$(MAILTRAP_API_TOKEN)
        MAILTRAP_INBOX_ID=$(MAILTRAP_INBOX_ID)
        MAILTRAP_ACCOUNT_ID=$(MAILTRAP_ACCOUNT_ID)
        AZURE_EMAIL_CONNECTION_STRING=$(AZURE_EMAIL_CONNECTION_STRING)
        AZURE_EMAIL_SENDER_ADDRESS=$(AZURE_EMAIL_SENDER_ADDRESS)
        AZURE_EMAIL_FORM_RECIEVER_ADDRESS=$(AZURE_EMAIL_FORM_RECIEVER_ADDRESS)
        APP_URL=$(APP_URL_DEV)
        EOF
